[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
rustflags = ["-C", "target-feature=+crt-static"] # controls linking with musl require to install 'brew install FiloSottile/musl-cross/musl-cross'
